This line result in "SassError: Expected digit."
The error message is following.

```
Uncaught Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected digit.
        ╷
 354 │   left: calc(--0.05rem - 1.2em);
         │                    ^
        ╵
  node_modules/@doabit/semantic-ui-sass/src/scss/elements/_label.scss 354:15  @import

```
This need to be changed for importing all packages.